/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './admin.html', './src/**/*.{js,html}'],
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#303031',
        'primary-fixed': '#e5e2e1',
        'inverse-primary': '#c9c6c5',
        'error-container': '#ffdad6',
        'secondary-fixed': '#ffdea5',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-secondary-container': '#785a1a',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#e9c176',
        outline: '#747878',
        'on-tertiary-fixed': '#1a1c1c',
        'surface-container-high': '#e9e8e7',
        'surface-variant': '#e4e2e2',
        'on-primary': '#ffffff',
        primary: '#000000',
        'surface-container': '#efeded',
        'surface-container-low': '#f5f3f3',
        'on-background': '#1b1c1c',
        'on-primary-container': '#858383',
        'primary-fixed-dim': '#c9c6c5',
        'secondary-container': '#fed488',
        'on-error': '#ffffff',
        'on-tertiary-container': '#838484',
        'surface-container-high': '#e9e8e7',
        'surface': '#fbf9f8',
        secondary: '#775a19',
        'on-surface': '#1b1c1c',
        'on-primary-fixed': '#1c1b1b',
        tertiary: '#000000',
        'outline-variant': '#c4c7c7',
        'tertiary-container': '#1a1c1c',
        'surface-container-highest': '#e4e2e2',
        'surface-bright': '#fbf9f8',
        'on-secondary-fixed-variant': '#5d4201',
        'on-tertiary-fixed-variant': '#454747',
        'on-surface-variant': '#444748',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#261900',
        'surface-dim': '#dbdad9',
        'on-tertiary': '#ffffff',
        'primary-container': '#1c1c1b',
        'tertiary-fixed': '#e2e2e2',
        'surface-tint': '#5f5e5e',
        background: '#fbf9f8',
        'on-primary-fixed-variant': '#474646',
        'inverse-on-surface': '#f2f0f0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '32px',
        'edge-margin-mobile': '24px',
        'edge-margin-desktop': '80px',
        'container-max': '1440px',
        'section-padding': '120px',
      },
      fontFamily: {
        'body-md': ['Hanken Grotesk'],
        'display-lg': ['Bodoni Moda'],
        'body-lg': ['Hanken Grotesk'],
        'label-caps': ['Hanken Grotesk'],
        'headline-lg-mobile': ['Bodoni Moda'],
        'headline-md': ['Bodoni Moda'],
        'headline-lg': ['Bodoni Moda'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['80px', { lineHeight: '96px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '32px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.15em', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '56px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
