export const products = [
  {
    id: 'midnight-solitaire-ring',
    name: 'Midnight Solitaire Ring',
    price: 'Price Upon Request',
    desc: 'A timeless solitaire featuring a hand-selected brilliant diamond set on 18K Ethiopian Gold, embodying the regal heritage of Zoskales.',
    tagline: 'Timeless elegance, forever yours',
    tryOnCategory: 'ring',
    tryOnImage: '/images/midnight-solitaire-ring.jpg',
  },
  {
    id: 'celestial-halo-necklace',
    name: 'Celestial Halo Necklace',
    price: 'Price Upon Request',
    desc: 'A luminous halo of diamonds encircling a radiant centerpiece, suspended from a delicate platinum chain inspired by celestial forms.',
    tagline: 'Radiance that transcends the ordinary',
    tryOnCategory: 'necklace',
    tryOnImage: '/images/celestial-halo-necklace.jpg',
  },
  {
    id: 'cascade-diamond-studs',
    name: 'Cascade Diamond Studs',
    price: 'Price Upon Request',
    desc: 'Brilliant diamond studs with a cascading pavé setting that captures light from every angle, crafted in pure Platinum 950.',
    tagline: 'Every angle, pure brilliance',
    tryOnCategory: 'earring',
    tryOnImage: '/images/cascade-diamond-studs.jpg',
  },
  {
    id: 'infinity-diamond-band',
    name: 'Infinity Diamond Band',
    price: 'Price Upon Request',
    desc: 'An unbroken eternity of pavé diamonds set in 18K Warm Rose Gold, symbolizing infinite devotion and timeless unity.',
    tagline: 'An unbroken circle of devotion',
    tryOnCategory: 'ring',
    tryOnImage: '/images/infinity-diamond-band.jpg',
  },
  {
    id: 'sovereign-diamond-pendant',
    name: 'Sovereign Diamond Pendant',
    price: 'Price Upon Request',
    desc: 'A majestic diamond pendant with talismanic significance, set in 18K Yellow Gold and inspired by the royal regalia of Aksum.',
    tagline: 'Majesty worn close to the heart',
    tryOnCategory: 'necklace',
    tryOnImage: '/images/sovereign-diamond-pendant.jpg',
  },
  {
    id: 'eternal-diamond-earrings',
    name: 'Eternal Diamond Earrings',
    price: 'Price Upon Request',
    desc: 'Graceful diamond drop earrings with graduated brilliance, designed for ceremonial grandeur and everyday splendor.',
    tagline: 'Grace that echoes through time',
    tryOnCategory: 'earring',
    tryOnImage: '/images/eternal-diamond-earrings.jpg',
  },
  {
    id: 'diamond-tennis-bracelet',
    name: 'Diamond Tennis Bracelet',
    price: 'Price Upon Request',
    desc: 'A flexible eternity tennis bracelet with perfectly matched diamonds, handcrafted for seamless elegance and enduring comfort.',
    tagline: 'Seamless luxury on the wrist',
    tryOnCategory: 'bracelet',
    tryOnImage: '/images/diamond-tennis-bracelet.jpg',
  },
  {
    id: 'diamond-riviera-necklace',
    name: 'Diamond Riviera Necklace',
    price: 'Price Upon Request',
    desc: 'A graduated cascade of hand-selected diamonds flowing from clasp to clasp, embodying the opulence of a royal Riviera.',
    tagline: 'A river of diamonds, a cascade of light',
    tryOnCategory: 'necklace',
    tryOnImage: '/images/diamond-riviera-necklace.jpg',
  },
];

export default products;
